CFLAGS = -g -Wall -I../4_stackqueue
hello: main.c graph.c dfs_traverse.c bfs_traverse.c mtly.c mtly1.c ../4_stackqueue/linkqueue.c | Makefile
	gcc $(CFLAGS) -o main main.c graph.c dfs_traverse.c bfs_traverse.c mtly.c mtly1.c ../4_stackqueue/linkqueue.c